import { reactive } from 'vue'
import { v4 as uuidv4 } from 'uuid'; // Importing uuid for unique ID generation

import projectImage1 from '@/assets/projects/Project1.svg';
import projectImage2 from '@/assets/projects/Project2.svg';
import projectImage3 from '@/assets/projects/Project3.svg';
import projectImage4 from '@/assets/projects/Project4.svg';
import projectImage5 from '@/assets/projects/Project5.svg';
import projectImage6 from '@/assets/projects/Project6.svg';
import projectImage7 from '@/assets/projects/Project7.svg';
import projectImage8 from '@/assets/projects/Project8.svg';

// Initialize state with sample projects
const state = reactive({
  projects: [
    {
      id: uuidv4(), // Unique ID
      title: 'LMS CyberEd: PWNEU CTF Platform Thesis Project',
      description: `LMS CyberEd: PWNEU CTF” Platform is an advanced Learning Management System (LMS) tailored specifically for cybersecurity education through Capture the Flag (CTF) challenges. This platform is designed to provide an interactive and engaging learning environment where students can develop and hone their cybersecurity skills in a practical, hands-on manner. The platform supports a wide range of CTF challenges, from basic to advanced levels, covering various cybersecurity domains.`,
      link: 'https://github.com/pwneu',
      image: projectImage1
      
    },
    {
      id: uuidv4(), // Unique ID
      title: 'AuthenText AI',
      description: `“AuthenText AI” is a sophisticated tool designed to detect AI-generated content with an emphasis on maintaining the authenticity of the human narrative. This project goes beyond conventional AI detection methods, focusing on preserving the integrity of academic and professional work. Whether dealing with content generated by ChatGPT, GPT-4, or other AI tools, AuthenText AI serves as a trusted guardian, ensuring that your content remains original and credible.`,
      link: 'https://github.com/sghangaan/AutthenTextAI-NEU.git',
      image: projectImage2
    },
    {
      id: uuidv4(), // Unique ID
      title: 'University Cinema Booking Ticket',
      description: `This University Cinema aims to provide a seamless ticketing experience, accessible anytime and anywhere. It aims to overcome the common challenges associated with onsite ticket reservations, ensuring a hassle-free process and enhancing the overall user and client experience. Specifically tailored for universities, this project offers an efficient, enhanced, and accessible way for academic institutions to facilitate ticket reservations for campus movie events and leverage an expansive reach of online channels and platforms for campus cinephiles.`,
      link: 'https://github.com/sghangaan/OnlineBooking-MovieTickets.git',
      image: projectImage3
    },
    {
      id: uuidv4(),// Unique ID
      title: 'PC Parts E-commerce Website',
      description: `"PC Parts E-commerce Website" is a fully functional online store built specifically for purchasing PC components. Developed using PHP, JavaScript, HTML, and CSS, this project showcases a modern, responsive e-commerce platform where users can browse, search, and purchase various PC parts, ranging from CPUs and GPUs to motherboards and peripherals. The website provides a seamless shopping experience with features like product filtering, a shopping cart, user authentication, and order management.`,
      link: 'http://ez-peasy.free.nf/index.php',
      image: projectImage4
    },
    {
      id: uuidv4(), // Unique ID
      title: 'Responsive Web Development Using Bootstrap for Beginners',
      description: `Responsive Web Development Using Bootstrap for Beginners" is a web development project aimed at introducing newcomers to the foundational concepts of responsive design. The project utilizes Bootstrap, a free front-end framework, to simplify the process of building responsive, mobile-first websites. The project covers essential Bootstrap components, such as grids, typography, buttons, forms, navigation, and modals, providing an accessible path for beginners to create professional-looking web pages.`,
      link: 'https://github.com/sghangaan/Beginner-WebDev-Using-Bootstrap.git',
      image: projectImage5
    },
    {
      id: uuidv4(),// Unique ID
      title: 'Design Patterns and Principles',
      description: `Design Patterns and Principles" is a comprehensive repository focused on implementing some of the most essential design patterns and software engineering principles in Java. This project serves as both an educational resource and a practical guide for developers aiming to create robust, scalable, and maintainable software systems. The repository not only demonstrates how to implement these patterns but also explains the underlying principles that make them effective.`,
      link: 'https://github.com/sghangaan/Software-Engineering_Designs-Patterns.git',
      image: projectImage6
    },
    {
      id: uuidv4(), // Unique ID
      title: 'CodeSculptorPro',
      description: `"CodeSculptorPro" is a specialized code analysis tool designed to assist developers in scrutinizing single-line code statements with a focus on declarations and assignment operations. The software leverages the first three stages of the compilation process—lexical analysis, syntax analysis, and semantic analysis—to provide detailed insights into the correctness and structure of various data types such as String, int, char, boolean, double, and float. This tool is particularly useful for beginners and educators who want to teach or learn the basics of code compilation in a simplified, focused environment.`,
      link: 'https://github.com/sghangaan/CodeSculptorPro.git',
      image: projectImage7
    },
    {
      id: uuidv4(), // Unique ID
      title: 'Mastering Data Structures and Algorithms in Java',
      description: `Mastering Data Structures and Algorithms in Java" is a meticulously designed course aimed at providing an in-depth understanding of the core concepts in computer science—data structures and algorithms. Through this course, learners will explore the intricacies of organizing data and the principles behind effective algorithmic problem-solving using Java. The course is structured to cater to both students and professionals, enabling them to strengthen their programming skills and apply them in real-world scenarios.`,
      link: 'https://github.com/sghangaan/Data-Structures-and-Algorithm.git',
      image: projectImage8
    }
  ]
})

const addProject = (project) => {
    project.id = uuidv4(); // Generate a new unique ID for the new project
    state.projects.push(project);
  }
  
  const updateProject = (updatedProject) => {
    const index = state.projects.findIndex((p) => p.id === updatedProject.id);
    if (index !== -1) {
      state.projects[index] = updatedProject; // Replace the project in the array
    }
  }
  
  const deleteProject = (id) => {
    state.projects = state.projects.filter((project) => project.id !== id);
  }
  
  export function useProjectStore() {
    return { state, addProject, updateProject, deleteProject };
  }

  