<template>
  <header class="bg-black p-4 fixed top-0 right-0 w-full z-50">
    <nav class="flex justify-between items-center">
      <!-- Logo Section -->
      <RouterLink to="/">
        <img src="../assets/navbar.svg" alt="Logo" class="h-100" />
      </RouterLink>

      <!-- Navigation Links (All point to Home) -->
      <div class="flex space-x-4">

        <RouterLink to="/" class="text-white hover:text-yellow-500">Home</RouterLink>
        <RouterLink to="/about" class="text-white hover:text-yellow-500">About</RouterLink>
        <RouterLink to="/projects" class="text-white hover:text-yellow-500">Project</RouterLink>
        <RouterLink to="/myprofile" class="text-white hover:text-yellow-500">Resume</RouterLink>
        <RouterLink to="/admin" class="text-white hover:text-yellow-500">Admin</RouterLink>
      </div>
    </nav>
  </header>

  <div class="min-h-screen bg-gray-100 pt-20">
    <!-- Projects Section -->
    <section class="container mx-auto p-4">
      <!-- Project Grid -->
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <!-- Project 1 -->
        <a href="https://github.com/pwneu"
          class="block bg-white shadow-lg rounded-lg overflow-hidden transition-transform transform hover:scale-105 hover:shadow-xl mb-4">
          <img src="../assets/projects/Project1.svg" alt="Project 1" class="w-full h-48 object-cover">
          <div class="p-4">
            <h3 class="text-xl font-semibold text-center">LMS CyberEd: PWNEU CTF Platform Thesis Project, June 2024 –
              Present</h3>
            <p class="mt-9 text-black-200 text-sm text-justify">LMS CyberEd: PWNEU CTF” Platform is an advanced Learning
              Management System (LMS) tailored specifically for cybersecurity education
              through Capture the Flag (CTF) challenges. This platform is designed to provide an interactive and
              engaging learning environment where
              students can develop and hone their cybersecurity skills in a practical, hands-on manner. The platform
              supports a wide range of CTF
              challenges, from basic to advanced levels, covering various cybersecurity domains.</p>
          </div>
        </a>

        <!-- Project 2 -->
        <a href="https://github.com/sghangaan/AutthenTextAI-NEU.git"
          class="block bg-white shadow-lg rounded-lg overflow-hidden transition-transform transform hover:scale-105 hover:shadow-xl mb-4">
          <img src="../assets/projects/Project2.svg" alt="Project 2" class="w-full h-48 object-cover">
          <div class="p-4">
            <h3 class="text-xl font-semibold text-center">AuthenText AI</h3>
            <p class="mt-4 text-black-200 text-sm text-justify">“AuthenText AI” is a sophisticated tool designed to
              detect
              AI-generated content with an emphasis on maintaining
              the authenticity of the human narrative. This project goes
              beyond conventional AI detection methods, focusing on
              preserving the integrity of academic and professional work.
              Whether dealing with content generated by ChatGPT,
              GPT-4, or other AI tools, AuthenText AI serves as a trusted
              guardian, ensuring that your content remains original and
              credible.</p>
          </div>
        </a>

        <!-- Project 3 -->
        <a href="https://github.com/sghangaan/OnlineBooking-MovieTickets.git"
          class="block bg-white shadow-lg rounded-lg overflow-hidden transition-transform transform hover:scale-105 hover:shadow-xl mb-4">
          <img src="../assets/projects/Project3.svg" alt="Project 3" class="w-full h-48 object-cover">
          <div class="p-4">
            <h3 class="text-xl font-semibold text-center">University Cinema Booking Ticket</h3>
            <p class="mt-4 text-black-200 text-sm text-justify">This University Cinema aims to provide a seamless
              ticketing experience, accessible anytime and anywhere. It
              aims to overcome the common challenges associated with
              onsite ticket reservations, ensuring a hassle-free process
              and enhancing the overall user and client experience.
              Specifically tailored for universities, this project offers an
              efficient, enhanced, and accessible way for academic
              institutions to facilitate ticket reservations for campus
              movie events and leverage an expansive reach of online
              channels and platforms for campus cinephiles.</p>
          </div>
        </a>

        <!-- Project 4 -->
        <a href="http://ez-peasy.free.nf/index.php"
          class="block bg-white shadow-lg rounded-lg overflow-hidden transition-transform transform hover:scale-105 hover:shadow-xl mb-4">
          <img src="../assets/projects/Project4.svg" alt="Project 4" class="w-full h-48 object-cover">
          <div class="p-4">
            <h3 class="text-xl font-semibold text-center">Ecommerce</h3>
            <p class="mt-4 text-black-200 text-sm text-justify">"PC Parts E-commerce Website" is a fully functional
              online store built specifically for purchasing PC
              components. Developed using PHP, JavaScript, HTML,
              and CSS, this project showcases a modern, responsive e-
              commerce platform where users can browse, search,
              and purchase various PC parts, ranging from CPUs and
              GPUs to motherboards and peripherals. The website
              provides a seamless shopping experience with features
              like product filtering, a shopping cart, user
              authentication, and order management.</p>
          </div>
        </a>

        <!-- Project 5 -->
        <a href="https://github.com/sghangaan/Beginner-WebDev-Using-Bootstrap.git"
          class="block bg-white shadow-lg rounded-lg overflow-hidden transition-transform transform hover:scale-105 hover:shadow-xl mb-4">
          <img src="../assets/projects/Project5.svg" alt="Project 5" class="w-full h-48 object-cover">
          <div class="p-4">
            <h3 class="text-xl font-semibold text-center">Tutorial WebDev Using Bootstrap</h3>
            <p class="mt-4 text-black-200 text-sm text-justify">Responsive Web Development Using Bootstrap for
              Beginners" is a web development project aimed at introducing newcomers to the
              foundational concepts of responsive design. The project utilizes Bootstrap, a free front-end framework, to
              simplify the process of
              building responsive, mobile-first websites. The project covers essential Bootstrap components, such as
              grids, typography, buttons,
              forms, navigation, and modals, providing an accessible path for beginners to create professional-looking
              web pages.</p>
          </div>
        </a>

        <!-- Project 6 -->
        <a href="https://github.com/sghangaan/Software-Engineering_Designs-Patterns.git"
          class="block bg-white shadow-lg rounded-lg overflow-hidden transition-transform transform hover:scale-105 hover:shadow-xl mb-4">
          <img src="../assets/projects/Project6.svg" alt="Project 6" class="w-full h-48 object-cover">
          <div class="p-4">
            <h3 class="text-xl font-semibold text-center">Software Engineering Repository for Designs Patterns</h3>
            <p class="mt-4 text-black-200 text-sm text-justify">Design Patterns and Principles" is a comprehensive
              repository focused on implementing some of the most essential design patterns and
              software engineering principles in Java. This project serves as both an educational resource and a
              practical guide for developers aiming to
              create robust, scalable, and maintainable software systems. The repository not only demonstrates how to
              implement these patterns but also
              explains the underlying principles that make them effective.</p>
          </div>
        </a>

        <!-- Project 7 -->
        <a href="https://github.com/sghangaan/CodeSculptorPro.git"
          class="block bg-white shadow-lg rounded-lg overflow-hidden transition-transform transform hover:scale-105 hover:shadow-xl mb-4">
          <img src="../assets/projects/Project7.svg" alt="Project 7" class="w-full h-48 object-cover">
          <div class="p-4">
            <h3 class="text-xl font-semibold text-center">CodeSculptor.PRO</h3>
            <p class="mt-4 text-black-200 text-sm text-justify">CodeSculptorPro" is a specialized code analysis tool
              designed to assist developers in scrutinizing single-line code statements with a focus
              on declarations and assignment operations. The software leverages the first three stages of the
              compilation process—lexical analysis,
              syntax analysis, and semantic analysis—to provide detailed insights into the correctness and structure of
              various data types such as String,
              int, char, boolean, double, and float. This tool is particularly useful for beginners and educators who
              want to teach or learn the basics of
              code compilation in a simplified, focused environment.</p>
          </div>
        </a>

        <!-- Project 8 -->
        <a href="https://github.com/sghangaan/Data-Structures-and-Algorithm.git"
          class="block bg-white shadow-lg rounded-lg overflow-hidden transition-transform transform hover:scale-105 hover:shadow-xl mb-4">
          <img src="../assets/projects/Project8.svg" alt="Project 8" class="w-full h-48 object-cover">
          <div class="p-4">
            <h3 class="text-xl font-semibold text-center">Data Structures and Algorithm</h3>
            <p class="mt-4 text-black-200 text-sm text-justify">Mastering Data Structures and Algorithms in Java" is a
              meticulously designed course aimed at providing an in-depth understanding of the core
              concepts in computer science—data structures and algorithms. Through this course, learners will explore
              the intricacies of organizing data and
              the principles behind effective algorithmic problem-solving using Java. The course is structured to cater
              to both students and professionals,
              enabling them to strengthen their programming skills and apply them in real-world scenarios.</p>
          </div>
        </a>

        <!-- Project 9 -->
        <a href="#"
          class="block bg-white shadow-lg rounded-lg overflow-hidden transition-transform transform hover:scale-105 hover:shadow-xl mb-4">
          <img src="https://via.placeholder.com/300" alt="Project 9" class="w-full h-48 object-cover">
          <div class="p-4">
            <h3 class="text-xl font-semibold text-center">CTF Modules</h3>
            <p class="mt-4 text-black-200 text-sm text-justify">Final project's description. Explain the significant
              learning or key outcomes from this project.</p>
          </div>
        </a>
      </div>
    </section>
  </div>
</template>

<script setup>
// No script needed for this.
</script>